<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-A6EPA854" name="Test" tests="3" failures="1" timestamp="18 May 2021 09:20:08 GMT" time="0.077" errors="0">
  <testcase name="@AfterMethod getresult" time="0.0" classname="ExtentReport.GenerateExtentReport">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at com.relevantcodes.extentreports.utils.ExceptionUtil.getExceptionHeadline(ExceptionUtil.java:25)
	at com.relevantcodes.extentreports.utils.ExceptionUtil.createExceptionInfo(ExceptionUtil.java:34)
	at com.relevantcodes.extentreports.ExtentTest.log(ExtentTest.java:131)
	at ExtentReport.GenerateExtentReport.getresult(GenerateExtentReport.java:51)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod getresult -->
  <testcase name="@AfterMethod getresult" time="0.0" classname="ExtentReport.GenerateExtentReport">
    <skipped/>
  </testcase> <!-- @AfterMethod getresult -->
  <testcase name="FailTestCase" time="0.014" classname="ExtentReport.GenerateExtentReport">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at ExtentReport.GenerateExtentReport.FailTestCase(GenerateExtentReport.java:39)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- FailTestCase -->
  <testcase name="PassTestCase" time="0.003" classname="ExtentReport.GenerateExtentReport"/>
  <testcase name="skiptestcase" time="0.003" classname="ExtentReport.GenerateExtentReport">
    <skipped/>
  </testcase> <!-- skiptestcase -->
</testsuite> <!-- Test -->
